version: "3.9"
services:
  fastify:
    image: node-fastify-demo:latest
    # ports: ## NOTE THIS CONFLICTS WITH REPLICA
    #   - 13000:3000
    deploy:
      replicas: 6
      placement:
        max_replicas_per_node: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure

