name: Build docker image for nodejs-serve

on:
  push:
  pull_request:
    paths:
      - nodejs-serve/**

defaults:
  run:
    shell: bash
    working-directory: nodejs-serve

jobs:
  image:
    name: Build and push docker image
    runs-on: ubuntu-latest

    steps:
      # mostly taken from https://github.com/marketplace/actions/build-and-push-docker-images
      - uses: actions/checkout@v2

      - uses: crazy-max/ghaction-docker-meta@v1
        id: docker_meta
        with:
          images: ghcr.io/jokester/nodejs-serve
          tag-sha: true # add git short SHA as Docker tag

      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1

      - name: login to ghcr
        if: false
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}

      - name: build and push to ghcr
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
